---
title: "Indicator Species Analysis"
author: "Amy Solman"
date: "06/10/2021"
output: html_document
---
This script will carry out Indicator Species Analysis 

Indicator Species Analysis will be used to answer the question:
Which species are found more often in the Arctic compared to the Antarctic?


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Clear workspace and load packages
```{r}
rm(list=ls())
graphics.off()

# library(ggpubr) #for making my boxplots
# library(FSA) #for dunn's test
# library(vegan) #for diversity indices
# library(ggplot2) #for making plots
# library(dplyr) #for manipulating data where you see %>% and computing summary stats
# install.packages("dendextend")
# library(dendextend) #for hierchical clustering
install.packages("indicspecies")
library(indicspecies)

```

Load data 
```{r}
#Load data files
load("../data-output/18S-my-sequence-data.RData") #load all our pre-processed data files

#load phyloseq object
##################################################BOTH POLES#################################################
ps <- readRDS("../data-output/18S-my-phyloseq-object.rds") #load unrarefied phyloseq object
ps.rar <- readRDS("../data-output/18S-my-phyloseq-object-rarefied.rds") #load rarefied phyloseq objectcol

# #Global abundances i.e. globally abundant, globally rare, globally intermediate
# ps.global.RA <- readRDS("../data-output/18S-all-rarefied-abundant.rds") #load rarefied globally abundant phyloseq object
# ps.global.RR <- readRDS("../data-output/18S-all-rarefied-rare.rds") #load rarefied globally rare phyloseq object
# ps.global.I <- readRDS("../data-output/18S-all-rarefied-intermediate.rds") #load rarefied globally abundant phyloseq object
# 
# #Both poles merged regional abundances
# ps.both.merged.RA <- readRDS("../data-output/18S-all-merged-rarefied-abundant.rds") #merged poles abundant phyloseq object
# ps.both.merged.RR <- readRDS("../data-output/18S-all-merged-rarefied-rare.rds") #merged poles rare phyloseq object
# ps.both.merged.I <- readRDS("../data-output/18S-all-merged-rarefied-intermediate.rds") #merged poles intermediate phyloseq object

#All glaciers merged abundances
ps.glaciers.merged.RA <- readRDS("../data-output/18S-all-glaciers-merged-rarefied-abundant.rds") #merged glaciers abundant phyloseq object
ps.glaciers.merged.RR <- readRDS("../data-output/18S-all-glaciers-merged-rarefied-rare.rds") #merged glaciers rare phyloseq object
ps.glaciers.merged.I <- readRDS("../data-output/18S-all-glaciers-merged-rarefied-intermediate.rds") #merged glaciers intermediate phyloseq object

# ##################################################ARCTIC#################################################
# ps.arc <- readRDS("../data-output/18S-arctic-rarefied.rds")
# ps.arc.RA <- readRDS("../data-output/18S-arctic-rarefied-abundant.rds") #load rarefied arctic abundant phyloseq object
# ps.arc.RR <- readRDS("../data-output/18S-arctic-rarefied-rare.rds") #load rarefied arctic rare phyloseq object
# ps.arc.I <- readRDS("../data-output/18S-arctic-rarefied-intermediate.rds") #load rarefied arctic intermediate phyloseq object
# 
# ##################################################ANTARCTIC#################################################
# ps.ant <- readRDS("../data-output/18S-antarctic-rarefied.rds")
# ps.ant.RA <- readRDS("../data-output/18S-antarctic-rarefied-abundant.rds") #load rarefied antarctic abundant phyloseq object
# ps.ant.RR <- readRDS("../data-output/18S-antarctic-rarefied-rare.rds") #load rarefied antarctic rare phyloseq object
# ps.ant.I <- readRDS("../data-output/18S-antarctic-rarefied-intermediate.rds") #load rarefied antarctic intermediate phyloseq object
```

Tutorial from: https://jkzorz.github.io/2019/07/02/Indicator-species-analysis.html 

Total Taxa
```{r}
#transform into relative abundances
ps.rar.rel = phyloseq::transform_sample_counts(ps.rar, function(x){x / sum(x)})

#get the asv table from our phyloseq object
counts <- data.frame(t(otu_table(ps.rar.rel)))

#check this worked correctly
rowSums(counts) #all rows should equal 1

#get the metadata from our phyloseq object
meta <- data.frame(sample_data(ps.rar.rel))

#run indicator species command
inv = multipatt(counts, meta$Pole, func = "r.g", control = how(nperm=999))

#view results
summary(inv) #25 asvs identified as specific to the Arctic
#no asvs identified as specific to Antarctic
```