---
title: "Redundancy Analysis"
author: "Amy Solman"
date: "09/10/2021"
output: html_document
---

http://dmcglinn.github.io/quant_methods/lessons/multivariate_models.html

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Clear workspace and load packages
```{r}
rm(list=ls())
graphics.off()

library(dplyr) #function coalesce
library(vegan) #rda function
```

Load Data
```{r}
#TOTAL DATASET
ps <- readRDS("../../results/18S/phylo-objects/18S-phyloseq-object-rarefied.rds")

#Total Abundant
ps.abun <- readRDS("../../results/18S/phylo-objects/18S-total-abundant.rds")
#Total Intermediate
ps.int <- readRDS("../../results/18S/phylo-objects/18S-total-intermediate.rds")
#Total Rare
ps.rare <- readRDS("../../results/18S/phylo-objects/18S-total-rare.rds")
```

Function for getting environmental data
```{r}
diversity_and_meta <- function(phylo){
  
#Get metadata of samples
samp_data <- data.frame(sample_data(phylo))

#list of variables we're interested in 
keeps <- c("Distance_To_Sea", "Elevation", "Water_Depth", "Sediment_Depth", "Total_Depth","Conductivity", "pH", "DOC_mgL.1",
           "Cl_merge", "SO4_merge", "Na_merge", "K_merge", "Mg_merge","Ca_merge", "HCO3_merge", "Radius", "EW", "NS")
samp_data <- samp_data[ , (names(samp_data) %in% keeps)]

#get cryoconite hole areas
area1 <- pi*samp_data$Radius^2
area2 <- pi*(samp_data$NS/2)*(samp_data$EW/2)
samp_data$Area <- coalesce(area1,area2)

# diversity_index <- estimate_richness(phylo)
# #Merge into datafrome
# samp_data$Observed <- diversity_index$Observed
# samp_data$Shannon <- diversity_index$Shannon

drops <- c("EW", "NS", "Radius")
samp_data <- samp_data[ , !(names(samp_data) %in% drops)]

#make sure data are numeric
samp_data[1:16] <- data.frame(lapply(samp_data[1:16],as.numeric))

#change sample names 
names(samp_data) <- c("Distance_To_Sea", "Elevation", "Water_Depth", "Sediment_Depth", "Total_Depth","Conductivity", "pH", "DOC_mgL.1", "Cl", "SO4", "Na", "K", "Mg","Ca", "HCO3", "Area")

  #remove columns with more than 50% missing variables
  samp_data_trim <- samp_data[ lapply( samp_data, function(x) sum(is.na(x)) / length(x) ) < 0.5 ]
  
  #Only keep complete cases
  samp_data_trim_complete <- samp_data_trim[complete.cases(samp_data_trim),]
  
return(samp_data_trim_complete)
}

#Test function
# phylo = ps
# res <- diversity_and_meta(ps)
```

Function for getting count data and aggregating by class
```{r}
agg_my_counts <- function(phylo, level){
  
  spe <- data.frame(t(otu_table(phylo)))

  #get out taxonomy table
  tax_tab <- data.frame(tax_table(phylo))
  #replace NAs with Unknown
  tax_tab[is.na(tax_tab)] <- "Unknown"
  colnames(spe) <- tax_tab[, level]

  #aggregate count data
  x <- t(spe)
  new_df=aggregate(x, by=list(rownames(x)),sum)
  new_counts <- t(new_df)
  colnames(new_counts) <- new_counts[1,]
  new_counts <- new_counts[-1,]
  df <- data.frame(new_counts)
  #make dataframe numeric
  df[] <- lapply(df, as.numeric)
  df <- df[,! names(df) %in% c("Unknown")]
  
  
  return(df)
}

#Function testing area
# phylo = ps
# level = "Phylum"
# df1 <- agg_my_counts(ps, "Phylum")
```

Function for performing redundancy analysis with stepwise selection of variables
```{r}
run_my_rda <- function(phylo, level, community){
  
  meta <- diversity_and_meta(phylo)
  df <- agg_my_counts(phylo, level)
  
  #trim df to have the same samples as meta
  df_trim <- df[(rownames(df) %in% rownames(meta)),]
  
  rda_res = rda(df_trim ~ . , data=meta, na.action = na.exclude)
  rda_res

  #Plot
  #plot a graph of results
  pdf(paste0("../../results/18S/graphs/RDA/", community, "-RDA.pdf"))
  plot(rda_res, display=c("sp", "cn"), scaling=0, main=paste0(community, " RDA AdjR= ", round(as.numeric(RsquareAdj(rda_res)[2]),digits=3)))
  #text(-0.4, 0.3, paste0("AdjR= ", round(as.numeric(RsquareAdj(rda_res)[2]),digits=3)))
  dev.off()
  
}

#Function testing area
phylo = ps
level = "Phylum"
community = "Total"
```
Additional steps to address
```{r}
  # #stepwise selection of variables
  # RDA1<-rda(df_trim~1,meta)
  # RDA2<-rda(df_trim~.,meta)
  # step.forward<-ordistep(RDA1,scope=formula(RDA2), direction="forward",perm.max=200,pstep=999)
  # 
  # #Find variance inflation ratios
  # vif.cca(rda_res) #all vif < 10
```

Run RDA
```{r}
run_my_rda(ps, "Phylum", "Total")
run_my_rda(ps.abun, "Phylum", "Abundant")
run_my_rda(ps.int, "Phylum", "Intermediate")
run_my_rda(ps.rare, "Phylum", "Rare")
```
