---
title: "Hierarchical Clustering"
author: "Amy Solman"
date: "06/10/2021"
output: html_document
---
This script will examine how samples cluster, based on Bray-Curtis dissimilarity.

I will colour code sample names to assess the extent to which samples from glaciers, regions and poles cluster.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Clear workspace and load packages
```{r}
rm(list=ls())
graphics.off()

# library(ggpubr) #for making my boxplots
# library(FSA) #for dunn's test
# library(vegan) #for diversity indices
# library(ggplot2) #for making plots
# library(dplyr) #for manipulating data where you see %>% and computing summary stats
install.packages("dendextend")
library(dendextend) #for hierchical clustering

```

Load data 
```{r}
#Load data files
load("../data-output/18S-my-sequence-data.RData") #load all our pre-processed data files

#load phyloseq object
##################################################BOTH POLES#################################################
ps <- readRDS("../data-output/18S-my-phyloseq-object.rds") #load unrarefied phyloseq object
ps.rar <- readRDS("../data-output/18S-my-phyloseq-object-rarefied.rds") #load rarefied phyloseq objectcol

#Global abundances i.e. globally abundant, globally rare, globally intermediate
ps.global.RA <- readRDS("../data-output/18S-all-rarefied-abundant.rds") #load rarefied globally abundant phyloseq object
ps.global.RR <- readRDS("../data-output/18S-all-rarefied-rare.rds") #load rarefied globally rare phyloseq object
ps.global.I <- readRDS("../data-output/18S-all-rarefied-intermediate.rds") #load rarefied globally abundant phyloseq object

#Both poles merged regional abundances
ps.both.merged.RA <- readRDS("../data-output/18S-all-merged-rarefied-abundant.rds") #merged poles abundant phyloseq object
ps.both.merged.RR <- readRDS("../data-output/18S-all-merged-rarefied-rare.rds") #merged poles rare phyloseq object
ps.both.merged.I <- readRDS("../data-output/18S-all-merged-rarefied-intermediate.rds") #merged poles intermediate phyloseq object

#All glaciers merged abundances
ps.glaciers.merged.RA <- readRDS("../data-output/18S-all-glaciers-merged-rarefied-abundant.rds") #merged glaciers abundant phyloseq object
ps.glaciers.merged.RR <- readRDS("../data-output/18S-all-glaciers-merged-rarefied-rare.rds") #merged glaciers rare phyloseq object
ps.glaciers.merged.I <- readRDS("../data-output/18S-all-glaciers-merged-rarefied-intermediate.rds") #merged glaciers intermediate phyloseq object

##################################################ARCTIC#################################################
ps.arc <- readRDS("../data-output/18S-arctic-rarefied.rds")
ps.arc.RA <- readRDS("../data-output/18S-arctic-rarefied-abundant.rds") #load rarefied arctic abundant phyloseq object
ps.arc.RR <- readRDS("../data-output/18S-arctic-rarefied-rare.rds") #load rarefied arctic rare phyloseq object
ps.arc.I <- readRDS("../data-output/18S-arctic-rarefied-intermediate.rds") #load rarefied arctic intermediate phyloseq object

##################################################ANTARCTIC#################################################
ps.ant <- readRDS("../data-output/18S-antarctic-rarefied.rds")
ps.ant.RA <- readRDS("../data-output/18S-antarctic-rarefied-abundant.rds") #load rarefied antarctic abundant phyloseq object
ps.ant.RR <- readRDS("../data-output/18S-antarctic-rarefied-rare.rds") #load rarefied antarctic rare phyloseq object
ps.ant.I <- readRDS("../data-output/18S-antarctic-rarefied-intermediate.rds") #load rarefied antarctic intermediate phyloseq object
```

Total Taxa
```{r}
#first get relative abundances
ps.rel.abund = phyloseq::transform_sample_counts(ps.rar, function(x){x / sum(x)})

#extract asv table
ps.rel.asv <- data.frame(phyloseq::otu_table(ps.rel.abund))
ps.rel.asv <- t(ps.rel.asv)

#calculate dissimilarities
bc_dist <- vegan::vegdist(ps.rel.asv, method = "bray")

#save as dendrogram
x <- as.dendrogram(hclust(bc_dist, method="ward.D2"))

#get colour codes
metadata <- data.frame(phyloseq::sample_data(ps.rel.abund))
colours <- c(Arctic = "red", Antarctic = "blue")
labels_colors(x) <- colours[metadata$Pole][order.dendrogram(x)]
#Plot
plot(x) #The dissimilarity of these samples is close to 1, suggesting their community compositions are all significantly dissimilar. There is clustering according to pole, so these communities are more similar.
```

Abundant Taxa
```{r}
#first get relative abundances
ps.rel.abund.ab = phyloseq::transform_sample_counts(ps.glaciers.merged.RA, function(x){x / sum(x)})

#extract asv table
ps.rel.asv.ab <- data.frame(phyloseq::otu_table(ps.rel.abund.ab))
ps.rel.asv.ab <- t(ps.rel.asv.ab)

#calculate dissimilarities
bc_dist.ab <- vegan::vegdist(ps.rel.asv.ab, method = "bray")
as.matrix(bc_dist.ab)[1:5, 1:5]

#save as dendrogram
x.ab <- as.dendrogram(hclust(bc_dist.ab, method="ward.D2"))

#get colour codes
metadata.ab <- data.frame(phyloseq::sample_data(ps.rel.abund.ab))
colours <- c(Arctic = "red", Antarctic = "blue")
labels_colors(x.ab) <- colours[metadata.ab$Pole][order.dendrogram(x.ab)]
#Plot
plot(x.ab) #The dissimilarity of these samples is close to 1, suggesting their community compositions are all significantly dissimilar. There is clustering according to pole, so these communities are more similar.
```

Intermediate Taxa
```{r}
#first get relative abundances
ps.rel.abund.i = phyloseq::transform_sample_counts(ps.glaciers.merged.I, function(x){x / sum(x)})

#extract asv table
ps.rel.asv.i <- data.frame(phyloseq::otu_table(ps.rel.abund.i))
ps.rel.asv.i <- t(ps.rel.asv.i)

#calculate dissimilarities
bc_dist.i <- vegan::vegdist(ps.rel.asv.i, method = "bray")
as.matrix(bc_dist.i)[1:5, 1:5]

#save as dendrogram
x.i <- as.dendrogram(hclust(bc_dist.i, method="ward.D2"))

#get colour codes
metadata.i <- data.frame(phyloseq::sample_data(ps.rel.abund.i))
colours <- c(Arctic = "red", Antarctic = "blue")
labels_colors(x.i) <- colours[metadata.i$Pole][order.dendrogram(x.i)]
#Plot
plot(x.i) #The dissimilarity of these samples is close to 1, suggesting their community compositions are all significantly dissimilar. There is clustering according to pole, so these communities are more similar.
```

Rare Taxa
```{r}
#first get relative abundances
ps.rel.abund.ra = phyloseq::transform_sample_counts(ps.glaciers.merged.RR, function(x){x / sum(x)})

#extract asv table
ps.rel.asv.ra <- data.frame(phyloseq::otu_table(ps.rel.abund.ra))
ps.rel.asv.ra <- t(ps.rel.asv.ra)

#calculate dissimilarities
bc_dist.ra <- vegan::vegdist(ps.rel.asv.ra, method = "bray")
as.matrix(bc_dist.ra)[1:5, 1:5]

#save as dendrogram
x.ra <- as.dendrogram(hclust(bc_dist.ra, method="ward.D2"))

#get colour codes
metadata.ra <- data.frame(phyloseq::sample_data(ps.rel.abund.ra))
colours <- c(Arctic = "red", Antarctic = "blue")
labels_colors(x.ra) <- colours[metadata.ra$Pole][order.dendrogram(x.ra)]
#Plot
plot(x.ra) #The dissimilarity of these samples is close to 1, suggesting their community compositions are all significantly dissimilar. There is clustering according to pole, so these communities are more similar.
```