---
title: "Network"
author: "Amy Solman"
date: "04/03/2021"
output: html_document
---

Network script taken from Jiao et al., (2020) Balance between community assembly processes mediates species coexistence in agricultural soil microbiomes across eastern China (https://github.com/shuojiao/Community-assembly-processes-and-species-coexistences-of-agricultural-soils-microbiome/blob/master/Network.R)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

rm(list=ls())
# Import bulk soil phyloseq data
#bulk.physeq = readRDS("/home/sam/data/fullCyc2_data/bulk_soil_physeq.RDS")
load("results/cleaned_files/cleanedfiles_3.RData")

#comun: A community table with samples as rows and taxa as columns. 

comun <- t(count_table_clean)

     require(Hmisc)
     require(igraph)

net<-function(comun){

     b_to<-rcorr(comun,type="spearman")
     r<-b_to$r
     p<-b_to$P
     r[r<0.6]<-0
     p<-p.adjust(p, method="fdr")
     q<-matrix(p,nrow=ncol(comun),ncol=ncol(comun))
     q[q<0.01]<-1
     q[q>0.01&q<1]<-0
     gg<-r*q
     diag(gg) <- 0
     g <- graph.adjacency(gg, weighted=TRUE, mode="undirected")
     g <- simplify(g)
     return(g)
}

x <- net(comun)

###net: the network generated by function net()
###Caculation of node-level topological features
network.degree <- degree(x)####Degree
network.betweenness <- betweenness(x)####Betweenness centrality
network.closeness <- closeness(x)####Closeness centrality

###Caculation of network-level topological features
length(V(net))###Number of nodes
length(E(net))###Number of edges
mean(degree(net))###Average degree
transitivity(net)###Clustering coefficient
average.path.length(net)###Average path length
diameter(net)###Network diameter
graph.density(net)###Graph density
```