---
title: "MultiCoLA Input File Prep"
author: "Amy Solman"
date: "19/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Clear workspace and import data
```{r}
rm(list=ls())
graphics.off()

#load packages
# install.packages("janitor")
# library(janitor) #to get column totals
# library(tibble) #to convert rowname to column and vice versa

#load phyloseq object
ps_pro <- readRDS("../results/16S/phylo-objects/16S-phyloseq-object-rarefied-decontam.rds") 
ps_euk <- readRDS("../results/18S/phylo-objects/18S-phyloseq-object-rarefied.rds") 
```

#Create and export a dataframe with ASVs as rows, Samples as columns, and Taxonomic classifications of ASVs as final columns of data frame
```{r}
my_phylo <- ps_pro

MultiCoLA_input_file_prep <- function(my_phylo){
  #extract ASV count table
  counts <- data.frame(otu_table(my_phylo), check.names = FALSE)
  #extract taxonomy
  taxa <- data.frame(tax_table(my_phylo))
  #merge and return dataframe
  counts_taxa <- cbind(counts, taxa)
  
  return(counts_taxa)
}
```
