---
title: "Raup-Crick"
author: "Amy Solman"
date: "14/04/2021"
output: html_document
---
#Raup-Crick code taken from Barrnet et al., (2020) (https://github.com/seb369/landuse_comm_assembly/blob/master/bNTI_calculation.Rmd) who developed their script from from Stegen et al., (2013) (https://github.com/stegen/Stegen_etal_ISME_2013/blob/master/bNTI_Local_Machine.r)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
# # Import bulk soil phyloseq data
# #bulk.physeq = readRDS("/home/sam/data/fullCyc2_data/bulk_soil_physeq.RDS")
# load("results/cleaned_files/cleanedfiles_3.RData")
# 
# #Let's make our data into a phyloseq object
# ASV = otu_table(data.frame(count_table_clean), taxa_are_rows = TRUE)
# TAX = tax_table(as.matrix(taxonomy))
# META	=	sample_data(data.frame(metadata, row.names = metadata$Run))
# my.ps <- phyloseq(ASV, TAX, META, tree_clean)
# 
# #check number of reads in each sample
# read.num <- data.frame("count" = colSums(otu_table(my.ps))) %>%
#   rownames_to_column(var="Run") %>%
#   inner_join(data.frame(sample_data(my.ps)), by="Run") %>%
#   arrange(-count) %>%
#   mutate(X.Sample=factor(Run, levels=Run))
# 
# #Check to make sure all of our samples are at or above 10000 reads
# ggplot(data=read.num, aes(x=Run, y=log10(count), fill = Glacier)) +
#   geom_bar(stat="identity")+
#   labs(x="Sample", y="Log10(Read count)")+
#   geom_hline(yintercept=log10(10000))+
#   theme(text=element_text(size=16),
#        axis.text.x=element_blank())

#Load data files
load("../Outputs/Sommers2020/cleanedfiles-abundance.RData")

#Phyloseq objects
my.ps <- readRDS("../Outputs/Sommers2020/my-ps-original.rds") #original full dataset, no rareification,
my.ps.rar <- readRDS("../Outputs/Sommers2020/my-ps-rarefied-total.rds") #rarefied dataset, total taxa
my.ps.rar.abun <- readRDS("../Outputs/Sommers2020/my-ps-rarefied-abundant.rds") #rarefied abundant taxa ONLY
my.ps.rar.rare <- readRDS("../Outputs/Sommers2020/my-ps-rarefied-rare.rds") #rarefied rare taxa ONLY
my.ps.rar.rel <- readRDS("../Outputs/Sommers2020/my-ps-rarefied-relative.rds") #rarefied relative abundance, total taxa
my.ps.rar.rel.abun <- readRDS("../Outputs/Sommers2020/my-ps-rarefied-relative-abundant.rds")#rarefied relative abundance abundant taxa ONLY
my.ps.rar.rel.rare <- readRDS("../Outputs/Sommers2020/my-ps-rarefied-relative-rare.rds") #rarefied relative abundance rare taxa ONLY

#Load dataframes
tot.diversity.data <- read.csv("../Outputs/Sommers2020/total-diversity-metadata.csv")
abun.diversity.data <- read.csv("../Outputs/Sommers2020/abundant-diversity-metadata.csv")
rare.diversity.data <- read.csv("../Outputs/Sommers2020/rare-diversity-metadata.csv")

```


#Now we need to rarefy the data to normalize the sequencing depth. We should also get a normalized dataset which gives relative abundance rather than readcounts.

```{r}
# #set a seed so we get the same results each time we run this
# set.seed(1961)
# #rarefy the data to equal sampling depths
# my.ps.rar <- rarefy_even_depth(my.ps)
# #get relative abundances
# my.ps.rar.rel <- transform_sample_counts(my.ps.rar, function(x) x/sum(x))
# 
# #subset to reduce size of dataset
# #my.ps.sub <- subset_samples(my.ps.rar, Glacier == "Taylor")
# #Remove ASVs not found in at least 3 samples
# asv.tab <- otu_table(my.ps.rar)
# asv.tab[asv.tab > 0] = 1
# asv.frq <- rowSums(asv.tab)
# asv.frq <- asv.frq[asv.frq > 20]
# my.ps.edit <- prune_taxa(names(asv.frq), my.ps.rar)

set.seed(1961)
myTaxa = names(sort(taxa_sums(my.ps.rar), decreasing = TRUE))
tax.to.keep <- sample(myTaxa, 100)
my.ps.edit = prune_taxa(tax.to.keep, my.ps.rar)

#check tree is rooted
is.rooted(phy_tree(my.ps.edit))  #TRUE

```

```{r}
# Function for calculating the distances in the null communities
RCbray_null_func <- function(i, freq.abd.df, alpha1, alpha2, N){
  # Get simulated communities and distance
  ## initally select OTUs weighted by their frequency. The number of OTUs selected should equal the richness of the samples.
  simcom1 = data.frame(table(sample(freq.abd.df$OTU, size=alpha1, replace=F, prob=freq.abd.df$freq)), stringsAsFactors = F)
  colnames(simcom1) = c("OTU","simcom1")
  simcom1$OTU = as.character(simcom1$OTU)
  simcom1 = inner_join(simcom1, freq.abd.df, by="OTU")
  simcom2 = data.frame(table(sample(freq.abd.df$OTU, size=alpha2, replace=F, prob=freq.abd.df$freq)), stringsAsFactors = F)
  colnames(simcom2) = c("OTU","simcom2")
  simcom2$OTU = as.character(simcom2$OTU)
  simcom2 = inner_join(simcom2, freq.abd.df, by="OTU")

  ## Now recruit OTUs based on their abundance in the metacommunity
  simcom1.abd = data.frame(table(sample(simcom1$OTU, size=N-alpha1, replace=T, prob=simcom1$p)), stringsAsFactors = F)
  colnames(simcom1.abd) = c("OTU","simcom1.abd")
  simcom1.abd$OTU = as.character(simcom1.abd$OTU)
  simcom1 = full_join(simcom1, simcom1.abd, by="OTU") %>%
    mutate(simcom1.abd = ifelse(is.na(simcom1.abd), 1, simcom1.abd)) %>%
    select(OTU, simcom1.abd)
  
  simcom2.abd = data.frame(table(sample(simcom2$OTU, size=N-alpha2, replace=T, prob=simcom2$p)), stringsAsFactors = F)
  colnames(simcom2.abd) = c("OTU","simcom2.abd")
  simcom2.abd$OTU = as.character(simcom2.abd$OTU)
  simcom2 = full_join(simcom2, simcom2.abd, by="OTU") %>%
    mutate(simcom2.abd = ifelse(is.na(simcom2.abd), 1, simcom2.abd)) %>%
    select(OTU, simcom2.abd)

  
  simcom = full_join(simcom1, simcom2, by="OTU")
  simcom[is.na(simcom)] = 0
  rownames(simcom) = simcom$OTU
  simcom$OTU = NULL
  
  null.dist = vegdist(t(simcom), method="bray")[1]
  return(null.dist)
}

# Main function for calculating RCbray
Calc_RCbray <- function(physeq, reps, nproc){
  # Get OTU table from phyloseq object
  otu.table = otu_table(physeq)
  
  # Get alpha diversity for each sample
  otu.PA.table = otu.table
  otu.PA.table[otu.PA.table > 0] = 1
  alpha.df = data.frame(Sample_ID = colnames(otu.PA.table), OTU.n = colSums(otu.PA.table), stringsAsFactors = F)
  
  # Get beta diversity matrix
  beta.table = as.matrix(vegdist(t(otu.PA.table), method="bray", diag=TRUE, upper=TRUE))
  
  ## Get metacommunity
  # Calculate the number of individuals in the meta community (Average read depth)
  N <- mean(apply(t(otu.table), 1, sum))
  
  # Calculate the average relative abundance of each taxa across communities
  p.m <- apply(t(otu.table), 2, mean)
  p.m <- p.m[p.m != 0]
  p <- p.m/N
  
  # Calculate the occurrence frequency of each taxa across communities
  otu.table.bi <- 1*(t(otu.table)>0)
  freq <- apply(otu.table.bi, 2, mean)
  freq <- freq[freq != 0]
  
  # Combine
  freq.abd.df = data.frame(p=p, freq=freq) %>%
    tibble::rownames_to_column(var="OTU") %>%
    filter(p != 0, freq != 0) %>%
    arrange(p)
  
  # For each pair of samples run the RCbray analysis
  comps = combn(alpha.df$Sample_ID, m=2, simplify = F)
  RCb.df = data.frame(Site1 = character(), Site2 = character(), RCb = numeric(), stringsAsFactors = F)
  for (j in seq(1, length(comps))){
    sam = comps[[j]]
    alpha1 = alpha.df[alpha.df$Sample_ID == sam[1],]$OTU.n
    alpha2 = alpha.df[alpha.df$Sample_ID == sam[2],]$OTU.n
    # Permute "reps" many times
    rep.list = seq(1, reps)
    null.list = mclapply(rep.list, RCbray_null_func, freq.abd.df=freq.abd.df, alpha1=alpha1, alpha2=alpha2, N=N, mc.cores=nproc)
    
    RCb = (length(null.list[null.list > beta.table[sam[1], sam[2]]]) + (0.5*length(null.list[null.list == beta.table[sam[1], sam[2]]])))/reps
    RCb = (RCb - 0.5)*2
    
    RCb.df = rbind(RCb.df, data.frame(Site1=sam[1], Site2=sam[2], RCb=RCb, stringsAsFactors = F))
  }
  
  RCb.df
  return(RCb.df)
}

```

```{r}
RCb.df = Calc_RCbray(my.ps.edit, 20, 20)
write.table(RCb.df, file="../Outputs/Sommers2020/RCb_df-total.txt", quote = F, sep = "\t")
```

###ABUNDANT TAXA
```{r}
set.seed(1961)
myTaxa = names(sort(taxa_sums(my.ps.rar.abun), decreasing = TRUE))
tax.to.keep <- sample(myTaxa, 100)
my.ps.edit.abun = prune_taxa(tax.to.keep, my.ps.rar.abun)

#check tree is rooted
is.rooted(phy_tree(my.ps.edit.abun))  #TRUE
```

```{r}
RCb.df = Calc_RCbray(my.ps.edit.abun, 20, 20)
write.table(RCb.df, file="../Outputs/Sommers2020/RCb_df-abundant.txt", quote = F, sep = "\t")
```

###RARE TAXA
```{r}
set.seed(1961)
myTaxa = names(sort(taxa_sums(my.ps.rar.rare), decreasing = TRUE))
tax.to.keep <- sample(myTaxa, 50)
my.ps.edit.rare = prune_taxa(tax.to.keep, my.ps.rar.rare)

#check tree is rooted
is.rooted(phy_tree(my.ps.edit.rare))  #TRUE
```

```{r}
RCb.df = Calc_RCbray(my.ps.edit.rare, 10, 20)
write.table(RCb.df, file="../Outputs/Sommers2020/RCb_df-rare.txt", quote = F, sep = "\t")
```